apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m
  serviceAccountName: flux-cert-manager
  chart:
    spec:
      chart: jetstack/cert-manager
      #version: 'v1.9.1'
      sourceRef:
        kind: HelmRepository
        name: jetstack
      interval: 1m
  values:
    installCRDs: true
    http_proxy: "http://192.170.240.154:32712"
    https_proxy: "http://192.170.240.154:32712"
    NO_PROXY: "10.233.0.0/18"

