apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: all
      spec:
        template:
          spec:
            containers:
              - name: manager
                env:
                  - name: "HTTPS_PROXY"
                    value: "http://192.170.240.154:32712"
                  - name: "NO_PROXY"
                    value: ".cluster.local.,.cluster.local,.svc,10.233.0.0/18"      
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/part-of=flux
